app = "bloxio-bots"
primary_region = "ams"

[build]

[env]
BOTS = "true"
NODE_ENV = "production"

[http_service]
internal_port = 3000
force_https = true
auto_stop_machines = false
auto_start_machines = true
min_machines_running = 1

[[vm]]
cpu_kind = "shared"
cpus = 1
memory = "512mb"
